[package]
name = "DataVisualizer"
version = "0.1.0"
edition = "2024"

[dependencies]

egui = '0.27.2'
eframe = '0.27.2'
serde = { version = '1.0', features = ['derive'] }
serde_json = '1.0'
csv = '1.3'
plotters = '0.3.5'
